### ISSUE TITLE
index.js:34

### ISSUE THREAD

**Issue by Romeck94** [dani69654/evm_scan_wallets#5]
Hi, I had this problem :
$ npm start

> script_generatemnem_check_balance@1.0.0 start
> node index.js

- Scanning blockchain
C:\--\evm_scan_wallets-main\index.js:34
    throw new Error(error.message || error)
          ^

Error: Unexpected error occurred
    at scan (C:\--\evm_scan_wallets-main\index.js:34:11)

**Comment by dani69654** [comment]
Add `console.log(error)` in the `catch` statement and write it here.

**Comment by zozidalom** [comment]
I have the same issue. Running Geth node for eth on localhost. What ethereum node did you use @dani69654?

_▰▰▱▱▱▱▱ Scanning blockchainError: Invalid JSON RPC response: ""
    at Object.InvalidResponse (D:\Development\Personal\evm_scan_wallets-main\evm_scan_wallets-main\node_modules\web3-core-helpers\lib\errors.js:43:16)
    at XMLHttpRequest.request.onreadystatechange (D:\Development\Personal\evm_scan_wallets-main\evm_scan_wallets-main\node_modules\web3-providers-http\lib\index.js:95:32)
    at XMLHttpRequestEventTarget.dispatchEvent (D:\Development\Personal\evm_scan_wallets-main\evm_scan_wallets-main\node_modules\xhr2-cookies\dist\xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (D:\Development\Personal\evm_scan_wallets-main\evm_scan_wallets-main\node_modules\xhr2-cookies\dist\xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpRequestError (D:\Development\Personal\evm_scan_wallets-main\evm_scan_wallets-main\node_modules\xhr2-cookies\dist\xml-http-request.js:349:14)
    at ClientRequest.<anonymous> (D:\Development\Personal\evm_scan_wallets-main\evm_scan_wallets-main\node_modules\xhr2-cookies\dist\xml-http-request.js:252:61)
    at ClientRequest.emit (node:events:390:28)
    at Socket.socketOnEnd (node:_http_client:471:9)
    at Socket.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)_

**Comment by dani69654** [comment]
@zozidalom Just an infura one

**Comment by dani69654** [comment]
Pull and try again
